import { GetServerSideProps } from 'next';
import {useEffect} from 'react';
import {getProfile} from '@/libs/profile-lib';
import Head from 'next/head';
import { applyTheme } from '@/libs/theme-lib';
import baseTheme from '@/libs/themes/basetheme';
import PublicNavbar from '../public-navbar';
import Image from 'next/image';
import Link from 'next/link';

const PublicLayout = (props:any) => {
    useEffect(() => {
        applyTheme(baseTheme);
    }, []);

    return (
        <div>
            <Head>
                <title>Flow:t!</title>
                <meta name="description" content="Generated by create next app" />                
            </Head>
            <PublicNavbar user={props.profile}></PublicNavbar>
            <div className="w-full pt-16">
                {props.children}
            </div>
            <footer className="footer">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className="logo">
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}

export default PublicLayout;

export const getServerSideProps:GetServerSideProps = async (context)=>{
    const profile = await getProfile(context.req);
    return {props: {profile, loggedIn: !!profile}};
};
