import { GetServerSideProps } from 'next';
import {useEffect} from 'react';
import {getProfile} from '@/libs/profile-lib';
import Head from 'next/head';
import { applyTheme } from '@/libs/theme-lib';
import baseTheme from '@/libs/themes/basetheme';
import PublicNavbar from '../public-navbar';
import Image from 'next/image';
import Link from 'next/link';

const PublicLayout = (props:any) => {
    useEffect(() => {
        applyTheme(baseTheme);
    }, []);

    return (
        <div>
            <Head>
                <title>Flow:t!</title>
                <meta name="description" content="Generated by create next app" />                
            </Head>
            <PublicNavbar user={props.profile}></PublicNavbar>
            <section className="header relative pt-32 items-center flex h-screen max-h-860-px">
                <div className="container mx-auto items-center flex flex-wrap">
                    <div className="w-full px-4 pt-32">
                        {props.children}
                    </div>
                </div>
            </section>
        </div>
    );
}

export default PublicLayout;

export const getServerSideProps:GetServerSideProps = async (context)=>{
    const profile = await getProfile(context.req);
    return {props: {profile, loggedIn: !!profile}};
};
